baseURL = 'https://mica.lgbt/'
languageCode = 'en-us'
title = 'Mica (dot ell gee bee tee)'

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "emacs"

[minify]
    [minify.tdewolff]
        [minify.tdewolff.html]
            keepComments = true
